#!/bin/bash

## Description: import given test data into ddev (database and configurations)
## Usage: initialize
## Example: "ddev initialize"

if ! command -v "git-lfs" &> /dev/null
then
    echo "COMMAND "git lfs" could not be found"
    echo "Please install git-lfs support, see: https://git-lfs.github.com/"
    exit
fi

git lfs pull
ddev import-db --src=.project/data/db.sql.gz
mkdir -p config/sites/main && cp .project/config/typo3/config.yaml config/sites/main/
cp .project/config/typo3/DdevConfiguration.php .Build/public/typo3conf/AdditionalConfiguration.php
ddev typo3cms install:setup
mkdir -p .Build/public/fileadmin
cd .Build/public && tar xf ../../.project/data/fileadmin.tar.gz
