#!/bin/bash

## Description: import given test data into ddev (database and configurations)
## Usage: initialize
## Example: "ddev initialize"

if ! command -v "git-lfs" &> /dev/null
then
    echo "COMMAND "git lfs" could not be found"
    echo "Please install git-lfs support, see: https://git-lfs.github.com/"
    exit
fi

echo "Fetching database and fileadmin"
git lfs pull
echo "Copy configuration"
mkdir -p .build/config/sites/main
cp .project/config/typo3/config.yaml .build/config/sites/main/
mkdir -p .build/public
cp .project/config/typo3/.htaccess .build/public/
mkdir -p .build/config/system
cp .project/config/typo3/settings.php .build/config/system/
cp .project/config/typo3/additional.php .build/config/system/

echo "Importing database"
ddev import-db --file=.project/data/db.sql.gz
echo "Provide fileadmin"
cd .build/public && tar xf ../../.project/data/fileadmin.tar.gz
echo "Run 'composer install'"
ddev composer install
ddev describe
echo "Thanks for supporting 'EXT:publications"
